const INITIAL_MINING_PROGRESS: { [key: string]: number } = {
  iron: 0,
  bronze: 0,
  silver: 0,
  gold: 0,
  platinum: 0,
  diamond: 0,
  titanium: 0,
};

const INITIAL_ORES: GameResourceOre[] = [
  {
    active: true,
    isDisplayed: true,
    amount: 0,
    miningHardness: 5,
    name: "Iron ore",
    sellingPrice: 1,
    type: "ore",
    unlocked: true,
    unlockedFor: 0,
    value: "iron",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    miningHardness: 10,
    name: "Bronze ore",
    sellingPrice: 2,
    type: "ore",
    unlocked: true,
    unlockedFor: 0,
    value: "bronze",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    miningHardness: 20,
    name: "Silver ore",
    sellingPrice: 5,
    type: "ore",
    unlocked: true,
    unlockedFor: 0,
    value: "silver",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    miningHardness: 60,
    name: "Gold ore",
    sellingPrice: 20,
    type: "ore",
    unlocked: false,
    unlockedFor: 2000,
    value: "gold",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 100,
    name: "Platinum ore",
    sellingPrice: 35,
    type: "ore",
    unlocked: false,
    unlockedFor: 5000,
    value: "platinum",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 200,
    name: "Diamond ore",
    sellingPrice: 100,
    type: "ore",
    unlocked: false,
    unlockedFor: 10000,
    value: "diamond",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Titanium ore",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedFor: 25000,
    value: "titanium",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw crystal",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedFor: 25000,
    value: "crystal",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw etherium",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedFor: 25000,
    value: "etherium",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw oxidium",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedFor: 25000,
    value: "oxidium",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw baseterium",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedFor: 25000,
    value: "baseterium",
  },
];

const INITIAL_ALLOYS: GameResourceAlloy[] = [
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Iron ingot",
    smeltingDifficulty: 5,
    smeltingRecipe: {
      iron: 10,
    },
    sellingPrice: 20,
    type: "alloy",
    unlocked: false,
    unlockedFor: 10,
    value: "iron",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Bronze ingot",
    smeltingDifficulty: 10,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedFor: 200,
    value: "bronze",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Silver bar",
    smeltingDifficulty: 20,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedFor: 200,
    value: "silver",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Gold bar",
    smeltingDifficulty: 10,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedFor: 200,
    value: "gold",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    name: "Platinum bar",
    smeltingDifficulty: 10,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedFor: 200,
    value: "platinum",
  },
];

function generateResources(): GameResource[] {
  const result: GameResource[] = [];
  INITIAL_ORES.forEach((ore) => {
    result.push(ore);
  });
  INITIAL_ALLOYS.forEach((alloy) => {
    result.push(alloy);
  });
  return result;
}

const INITIAL_RESOURCES: GameResource[] = generateResources();

export { INITIAL_RESOURCES, INITIAL_MINING_PROGRESS };
