const INITIAL_ORES: GameResourceOre[] = [
  {
    active: true,
    isDisplayed: true,
    amount: 0,
    miningHardness: 5,
    name: "Iron ore",
    sellingPrice: 1,
    type: "ore",
    unlocked: true,
    unlockedAtHqLevel: 1,
    value: "iron_ore",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    miningHardness: 10,
    name: "Bronze ore",
    sellingPrice: 2,
    type: "ore",
    unlocked: true,
    unlockedAtHqLevel: 1,
    value: "bronze_ore",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    miningHardness: 20,
    name: "Silver ore",
    sellingPrice: 5,
    type: "ore",
    unlocked: true,
    unlockedAtHqLevel: 2,
    value: "silver_ore",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    miningHardness: 60,
    name: "Gold ore",
    sellingPrice: 20,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 3,
    value: "gold_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 100,
    name: "Platinum ore",
    sellingPrice: 35,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 4,
    value: "platinum_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 200,
    name: "Diamond ore",
    sellingPrice: 100,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 5,
    value: "diamond_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Titanium ore",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 6,
    value: "titanium_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw crystal",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 7,
    value: "crystal_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw etherium",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 8,
    value: "etherium_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw oxidium",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 9,
    value: "oxidium_ore",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    miningHardness: 500,
    name: "Raw baseterium",
    sellingPrice: 250,
    type: "ore",
    unlocked: false,
    unlockedAtHqLevel: 9,
    value: "baseterium_ore",
  },
];

const INITIAL_ALLOYS: GameResourceAlloy[] = [
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Iron ingot",
    smeltingDifficulty: 5,
    smeltingRecipe: {
      iron: 10,
    },
    sellingPrice: 20,
    type: "alloy",
    unlocked: false,
    unlockedAtHqLevel: 2,
    value: "iron_alloy",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Bronze ingot",
    smeltingDifficulty: 10,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedAtHqLevel: 3,
    value: "bronze_alloy",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Silver bar",
    smeltingDifficulty: 20,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedAtHqLevel: 4,
    value: "silver_alloy",
  },
  {
    active: false,
    isDisplayed: true,
    amount: 0,
    name: "Gold bar",
    smeltingDifficulty: 10,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedAtHqLevel: 5,
    value: "gold_alloy",
  },
  {
    active: false,
    isDisplayed: false,
    amount: 0,
    name: "Platinum bar",
    smeltingDifficulty: 10,
    smeltingRecipe: {
      bronze: 10,
    },
    sellingPrice: 50,
    type: "alloy",
    unlocked: false,
    unlockedAtHqLevel: 6,
    value: "platinum_alloy",
  },
];

function generateResources(): GameResource[] {
  const result: GameResource[] = [];
  INITIAL_ORES.forEach((ore) => {
    result.push(ore);
  });
  INITIAL_ALLOYS.forEach((alloy) => {
    result.push(alloy);
  });
  return result;
}

const INITIAL_RESOURCES: GameResource[] = generateResources();

export { INITIAL_RESOURCES };
